### PR TITLE
Style cleanup

### PR DESCRIPTION
**Pull request by proski**
Just some housekeeping to avoid such trivial changes in other pull requests. Should be completely uncontroversial.

*  Remove trailing space, expand tabs, add final newlines
*  Avoid wildcard import

### CODE REVIEW

**Review by jakub-bochenski — APPROVED** [review]

**Comment by jakub-bochenski** [comment]
lets merge this tomorrow to avoid conflicts unless we hear from @jimklimov  before

**Comment by jimklimov** [comment]
LGTM, and I wonder if this is too conservative, i think there were quite a few indentations to take care of, unless i'm mixing up codebases i've seen ;)

A good non controversial start in any case.

**Comment by proski** [comment]
> LGTM, and I wonder if this is too conservative, i think there were quite a few indentations to take care of, unless i'm mixing up codebases i've seen ;)
> 
> A good non controversial start in any case.

Thank you for merging.

I tried "Organize Includes" in Eclipse, but it reorders the includes everywhere. If there is any formatter that is standard for Jenkins code, I would be happy to apply it.

**Comment by jakub-bochenski** [comment]
Not sure about Jenkins code, but you can do much worse than using google style guide. It comes with good support for formatting and validation (fmt-maven-plugin, checkstyle-maven-plugin)

**Comment by proski** [comment]
Google style quite has two formats, `google` and `aosp`, and essentially no configuration. The `google` format uses 2 space indent, which is too different from the 4 space indent used in the code now. The `aosp` format has its downsides too, but at least it's possible to see where it's fixing most outrageous format sins in the code. Maybe fixing them would be a good first step.

**Pull request merged**
