### PR TITLE
StashRepository: Use StringUtils.containsIgnoreCase() and StringUtils.isEmpty()

### PR DESCRIPTION
**Pull request by proski**
```
*  StashRepository: Use StringUtils.containsIgnoreCase() and StringUtils.isEmpty()
   
   This improves readability of the code in isPhrasesContain(). It also
   fixes a low-priority FindBugs warning.
```

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
> triggers a FindBugs warning.

Where is that warning triggered? I see `No errors/warnings found` on the CI build.

**Comment by proski** [comment]
It is only reported if the threshold set to low. Just like the `Name` member. It is also reported by the SpotBugs plugin in Eclipse.

**Comment by jakub-bochenski** [comment]
Thanks for the explanation.

I don't think it's a good idea to change the code to a more verbose version just to satisfy FB. 

I couldn't find a full description of this issue (e.g on https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html), maybe I'm misunderstanding something. Could you maybe send me a link to full description?

**Comment by proski** [comment]
Here's the description: http://findbugs.sourceforge.net/bugDescriptions.html#DM_CONVERT_CASE

I realize that some issues cannot be fixed without making the code harder to read. This PR is adding code, but just a little bit. The change is just making the code more explicit.

If you don't like it, I can close it.

I think we should switch to using SpotBugs, which is more actively maintained. That would give us a better picture of what issues need to be fixed.

**Comment by proski** [comment]
Rewritten using `StringUtils`. The code is actually more readable now.

SpotBugs also detects a low-priority warning in the original code. We'll be updated from FundBugs to SpotBugs when we update the parent POM to the latest version. It's recommended to keep the parent POM up to date, as it updates the development tools without updating the requirements. I plan to do it once #68 is merged. Otherwise I would need to add an exception for the code removed in that PR.

The parent POM recommends using Low SpotBugs threshold:
```
<!-- Defines a SpotBugs threshold. Use "Low" to discover low-priority bugs.
         Hint: SpotBugs considers some real NPE risks in Jenkins as low-priority issues, it is recommended to enable it in plugins.
      -->
    <spotbugs.threshold>${findbugs.threshold}</spotbugs.threshold>
```

**Comment by jakub-bochenski** [comment]
Agree that we should update parent pom and switch to spotbugs

**Review by jakub-bochenski — APPROVED** [review]

**Pull request merged**
