### PR TITLE
Fix FindBugs warnings about StashBuildTrigger#job being null

### PR DESCRIPTION
**Pull request by proski**
Move startJob() and its dependencies from StashBuildTrigger to
StashRepository. StashBuildTrigger objects can have a null job field, but
it's impossible for StashRepository, which is instantiated once a
non-null job is passed to StashBuildTrigger#start().

### CODE REVIEW

**Comment by proski** [comment]
The FindBugs issue causing the failure will be fixed when #67 is merged. This PR will be rebased.

**Comment by proski** [comment]
Rebased, no FindBugs issues anymore.

**Review by jakub-bochenski — APPROVED** [review]

**Comment by jakub-bochenski** [comment]
Tried to resolve conflicts but I broke it. Can you take a look @proski ?

**Comment by proski** [comment]
> Tried to resolve conflicts but I broke it. Can you take a look @proski ?

No problem, PRs that move code don't play well with others.

I've rebased the PR. All the tests from `StashBuildTriggerTest.java` have been moved to `StashRepositoryTest.java`, so `StashBuildTriggerTest.java` is gone. No need to worry, #93 will add that file again.

**Comment by jakub-bochenski** [comment]
... and there are conflicts again because I merged #98 :)

**Comment by proski** [comment]
> ... and there are conflicts again because I merged #98 :)

No problem, resolved.

**Pull request merged**
