### PR TITLE
Fix incorrect logger names.

### PR DESCRIPTION
**Pull request by andham**

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Thanks for the PR, but actually could you use the CP-firendly `MethodHandles.lookup().lookupClass()`?

https://www.javaworld.com/article/2074637/portable-logger-names-with-java-7-method-handles.html

**Comment by jakub-bochenski** [comment]
@proski I tried to add you too as reviewer but can't. 
Anyhow will appreciate your feedback on this and other PRs given the amount of work you've done recently.

**Comment by proski** [comment]
Looks good to me. PR #43 removes the logger from `StashPostBuildComment.java`, so there would be some trivial conflict, but it's OK. I'm ready to update my PR quickly if this PR is merged first.

**Comment by proski** [comment]
> Thanks for the PR, but actually could you use the CP-firendly `MethodHandles.lookup().lookupClass()`?
> 
> https://www.javaworld.com/article/2074637/portable-logger-names-with-java-7-method-handles.html

I like the idea of using the code that doesn't need to be updated when copied.

It's surprising it's not used in Jenkins code or in any Jenkins "PR builder" plugins. But it is used in some Jenkins plugins, e.g. https://github.com/jenkinsci/logstash-plugin/blob/master/src/main/java/jenkins/plugins/logstash/persistence/BuildData.java

Jenkins core uses `getClass().getName()` is a few places, which is compact, but requires non-static context and may be expensive if there are many objects of a class.

**Comment by jakub-bochenski** [comment]
> It's surprising it's not used in Jenkins code or in any Jenkins "PR builder" plugins. But it is used in some Jenkins plugins, e.g. https://github.com/jenkinsci/logstash-plugin/blob/master/src/main/java/jenkins/plugins/logstash/persistence/BuildData.java

I think if you check git blame, you will see why https://github.com/jenkinsci/logstash-plugin/commit/3f07de719bad0c3008e4385c0e8a78be7bfc18c6 :)

**Review by jakub-bochenski — APPROVED** [review]
I went ahead and updated the logger expressions myself

**Comment by proski** [comment]
Looks good to me. Actually, there are many "old style" logger initializations, but we can convert them separately.

**Pull request closed without merging**
