### PR TITLE
Format java code and keep it formatted

### PR DESCRIPTION
**Pull request by jakub-bochenski**
This will format the files when run locally, and fail the build if run on Jenkins

### CODE REVIEW

**Comment by proski** [comment]
In general, I'm OK with reformatting.

Have you considered the "aosp" style? It would keep the indent and allow us to see the code history better. The "google" style touches almost every line.

Please run sortpom on the first commit, the formatting is off.

I confirm that I'm getting the same code after formatting. It's very important to check before merging, so we don't revert any patch accidentally.

Eclipse complains about pom.xml when importing the code:

```
No marketplace entries found to handle fmt-maven-plugin:2.8:format in Eclipse.  Please see Help for more information.
```

But that's not the only issue, it's also complaining about javadoc:

```
No marketplace entries found to handle maven-javadoc-plugin:2.10.4:javadoc in Eclipse.  Please see Help for more information.
```

So it's probably OK. Maybe I'll need to install some Eclipse addon or just tell Eclipse to ignore it.

**Comment by jakub-bochenski** [comment]
> Have you considered the "aosp" style? It would keep the indent and allow us to see the code history better. The "google" style touches almost every line.

Yes, but you can just do `git blame -w` and the changes are gone (also supported in most IDEs). 

My preference for google over asop is because google is a more popular and expected choice for a non android project :). If you think this is a big issue I'm OK to change it.

> Please run sortpom on the first commit, the formatting is off.

Good catch I only formatted everything on second commit.

> Eclipse complains about pom.xml when importing the code:

I think this is related to m2e integration. M2e plugin has "connectors" for each plugin (or I should say needs one for each plugin). The worst thing that can happen is that given plugin won't have any effect during eclipse builds, which is fine for formatting and javadoc (I expect people would just configure formatting in Eclipse directly)

**Comment by proski** [comment]
The choice of the style is not a big issue for me.

Thanks for the explanation of the Eclipse issue, it's approximately what I suspected.

**Comment by jakub-bochenski** [comment]
OK, I've pushed the cleaned up version

**Comment by proski** [comment]
Thank you! Looks good to me. Let's get it merged. I'll update my PRs on top of this.

**Pull request merged**
