### PR TITLE
Update jenkinsci repository with PRs merged into original author's repo

### PR DESCRIPTION
**Pull request by jimklimov**
@nemccarthy "upstream" repository has integrated a couple of PRs from here and there, a year ago. Isn't it time to promote them onwards?

### CODE REVIEW

**Comment by jimklimov** [comment]
Pinging @nemccarthy as the only maintainer, to get this PR moving forward :)

**Comment by jakub-bochenski** [comment]
I would rather review them and possibly integrate one by one. 
Also I would rather first just push out a new release with only simple bugfixes like #26

**Comment by jimklimov** [comment]
Makes sense to (update and) merge them separately...

**Comment by jakub-bochenski** [comment]
OK, closing this one then

**Pull request closed without merging**
