### PR TITLE
Increase socket timeout to 30s

### PR DESCRIPTION
**Pull request by andham**
Depending on the infrastructure, the current socket timeout of 15s can be too short. Due to the current code a socket timeout causes rebuilding PRs multiple times, see https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/101.
This fix increases the socket timeout which prevents timeouts in my environment. However, it does not solve the code issue causing rebuilding PRs multiple times should a timeout occur (should be handled in a separate fix).
A future improvement could be to have the timeout(s) configurable.

### CODE REVIEW

**Comment by proski** [comment]
I would make HTTP_CONNECTION_TIMEOUT_SECONDS 30 seconds as well. Socket timeout is for a single socket operation, which may include exchanging multiple TCP packets. So is setting up the TCP connection.

**Comment by jakub-bochenski** [comment]
I would rather expose this setting to be configurable instead. 

30 seconds is a long time for socket timeout. Our stash has some load problems, but I've never seen the socket timeout happen in the logs.

**NOTE:** you can install this version if you need it ASAP. Enable incrementals update center, then install version [1.9-rc231.5bb56ec50dfa](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/stash-pullrequest-builder/1.9-rc231.5bb56ec50dfa/)

Details: https://github.com/jenkinsci/jep/tree/master/jep/305

**Comment by proski** [comment]
> I would rather expose this setting to be configurable instead.
> 
> 30 seconds is a long time for socket timeout. Our stash has some load problems, but I've never seen the socket timeout happen in the logs.

We should balance the configurability against the UI complexity. Very few users would want to change the socket timeout it it's reasonable. An unreasonable timeout to me is something that annoys users frequently and a lot (think frequency multiplied by annoyance of a single incident).

Waiting for five minutes for a connection would be annoying for someone waiting for the PR build. But it would only matter if the network or the Stash server is misconfigured, which won't happen too often.

On the other hand, random failures due to timeouts would be annoying even if everything is configured correctly but the load is too high. That can happen more often, so it's better to have some protection against it.

If somebody cared to increase the timeout, it's an evidence to me that we are too much on the "short" side.

**Comment by andham** [comment]
Thanks @proski. We could possible make this configurable via some system property should someone care to tweak the values, but that should IMHO be a future PR (by someone that wants that feature). I spent about a day trying to figure out why it didn't work when I upgraded the plugin until I found the reported issue I linked to and eventually figured out that just increasing the socket time a bit solved it for my environment (fairly complicated infrastructure with firewalls). As you can se in the linked issue I'm not the only one who has this issue.

**Comment by jakub-bochenski** [comment]
In our setup we sometimes have problems with unclosed sockets piling up leading to a service degradation.  
Also twice longer time is twice as much logs to check when something fails. 
It's not as simple as longer timeout = easier.

Anyhow, what I don't get is why is it such a problem to add a configuration field. 
I think it would actually improve the user exerience if there was a global configuration like the one in [stash notifier](https://github.com/jenkinsci/stashnotifier-plugin/blob/master/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L452).
For one thing you wouldn't have to restate the same stash URL for every pull request job.

**Review by jakub-bochenski — CHANGES_REQUESTED** [review]
See discussion above

**Comment by proski** [comment]
Good point about the global configuration! It's a chore to click through every pull request builder to change some setting. The timeouts would work fine. It would be trickier if the same setting is tunable both globally and for the project. Even a simple boolean becomes tri-state (true, false, system default).

It would be even better to share socket settings between plugins, but I don't know if there is a mechanism for that.

Speaking of the defaults, StashNotifier is using 60 seconds for socket timeouts and appears to be using defaults for the rest. Make sure to check the `1.x` branch, `master` is stale there.

https://github.com/jenkinsci/stashnotifier-plugin/blob/c5a3453337a90a4934b4f6896fc7700bf003c67c/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L455

By the way, it looks like StashNotifier is using the new Apache HTTP API. Stash PullRequest Builder needs to update to it to fix the remaining warnings.

**Comment by jakub-bochenski** [comment]
> It would be even better to share socket settings between plugins, but I don't know if there is a mechanism for that.

There is a JRE system property we could use, but I think in case of Jenkins it makes sense to expose it per-plugin. Different plugins are probably going to talk to different servers so it's likely one setting might not fit all. 

> By the way, it looks like StashNotifier is using the new Apache HTTP API. Stash PullRequest Builder needs to update to it to fix the remaining warnings.

That would be nice, probably we could get rid of that copy-pasted EasySslProtocolFactory

**Comment by andham** [comment]
Wrt to migrating to Apache HTTP API that was already done in the original git repo. Not sure why that was not included when "forking". See https://github.com/nemccarthy/stash-pullrequest-builder-plugin/commit/8ffbe76af2344c0b92ecdf26514a2d5214a9996d
There is also one other commit that was missed (https://github.com/nemccarthy/stash-pullrequest-builder-plugin/commit/6f0fec874cd8e7c36d3697260853305c517aa919).

**Comment by proski** [comment]
I wasn't aware of the http change, I was trying to do it myself and got stuck in details. Thank you!

The pipeline issue is a big change, it should be done very carefully. I think we'll get to it soon.

**Comment by proski** [comment]
I actually like how git plugin deals with a large number of options. I can select additional behaviors from the list. I can select additional clone behaviors, additional checkout behaviors and so on. I don't have to configure everything, just the aspects I care about. And the great thing is, I will see those non-standard settings right away when I open the project configuration, without clicking on "Advanced".

Likewise, this plugin can have:

* Advanced Stash API behavior - timeouts, ignoring SSL certificates
* Advanced PR selection behavior - checking merge status, matching branch names
* Advanced comment behavior - custom text, removing old comments
* Advanced build behavior - canceling and aborting running jobs
* Advanced post-build behavior - merge on success

**Comment by andham** [comment]
Regardless of the possibility of configuring things in the UI (or elsewhere) I think that stuff like timeouts should be as consistent as possible, at least for access to the same server. It doesn't make sense that the stash-pullrequest-builder-plugin uses different default timeouts than e.g. stashNotifier.

**Comment by proski** [comment]
> Regardless of the possibility of configuring things in the UI (or elsewhere) I think that stuff like timeouts should be as consistent as possible, at least for access to the same server. It doesn't make sense that the stash-pullrequest-builder-plugin uses different default timeouts than e.g. stashNotifier.

That would require some infrastructure in Jenkins, a unified "external connection configuration". No single plugin can do it on its own and expect other plugins to use those settings without creating a dependency between plugins.

**Comment by andham** [comment]
I was just thinking that we should try to align these settings in this plugin with how it's in e.g. stashNotifier. No reason why there should be different defaults.
As it is now, we have no problems with timeouts with the git plugin or stashNotifier, but stash-pullrequest-builder-plugin sometimes time out.

**Comment by proski** [comment]
> I was just thinking that we should try to align these settings in this plugin with how it's in e.g. stashNotifier. No reason why there should be different defaults.
> As it is now, we have no problems with timeouts with the git plugin or stashNotifier, but stash-pullrequest-builder-plugin sometimes time out.

I have no problem with 30 seconds, but others object. That said, I believe 15 seconds should be sufficient for a good setup.

It's possible that using post-webhooks and the Bitbucket pull request builder would help you eliminate the delays, as it uses notifications, not polling. I really need to try it before I can recommend it to others.

**Comment by jakub-bochenski** [comment]
@proski Reposting this from #56, lets continue the discussion here

> Another approach would be to implement a separate "Stash service configuration" plugin that would let users configure one or many Stash services in the global Jenkins configuration. Both this plugin and Stash Notifier could use that information.

I was thinking: let's first try and reuse what the notifier plugin provides As a next step we could contact that plugin's maintainers about extracting the common parts.

**Review by jakub-bochenski — APPROVED** [review]
I though I will have more time to work on the global configuration myself. 
Sadly I'm too busy to work on that ATM.

Since there is apparently more people asking to increase the timeout, than not I think we should merge this.
@proski @jimklimov  any comments before I go ahead?

**Comment by proski** [comment]
I think we can increase the timeout to 30 seconds now and work on the global configuration later. There are cases when the network is slow temporarily. 30 seconds seems a good compromise to me. #69 adds a global configuration section in the last commit, so it can be expanded eventually.

**Pull request merged**
