### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by jakub-bochenski**
Let's start by enabling CI builds.

CC @jimklimov

### CODE REVIEW

**Review by jimklimov — APPROVED** [review]

**Comment by jimklimov** [comment]
Should the component also get registered on the CI Jenkins cloud service? The PR was not auto-tested, right?

**Comment by jakub-bochenski** [comment]
Per https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-ci.jenkins.io it should not be needed.
Probably something is disabled in project settings. Unfortunately I [still have no write access](https://groups.google.com/d/msg/jenkinsci-dev/oRBRP5-sZe4/Ul_RhEBpFAAJ) :(
Did you get write access to this repo?

**Comment by jimklimov** [comment]
Access works now, fixed a few minutes back on IRC.

**Comment by jakub-bochenski** [comment]
> Access works now, fixed a few minutes back on IRC.

Indeed. But I think we still need somebody with admin to reset the webhooks settings for this repository.
AFAIR jenkinsci organization defines default hooks for http://ci.jenkins.io/ but it seems this repository is overriding them.

**Comment by batmat** [comment]
Try to close/reopen this. Jenkinsfile are taken in account only is the PR submitter has Write access for secu reasons.

**Comment by jakub-bochenski** [comment]
Closing as per above comment

**Comment by jakub-bochenski** [comment]
Whoops! It went directly to master now.
At least it seems to be working now: https://ci.jenkins.io/job/Plugins/job/stash-pullrequest-builder-plugin/job/master/

**Comment by jimklimov** [comment]
https://ci.jenkins.io/job/Plugins/job/stash-pullrequest-builder-plugin/view/change-requests/job/PR-28/ also  appeared now

**Comment by batmat** [comment]
Yeah, you might be hitting the ongoing issue about ignored PRs also. I was going to advise to merge this without PR build exceptionally given the low risk here. But fine if you pushed directly to master (though I guess avoid doing this too often :-))

**Comment by jakub-bochenski** [comment]
And it seems the first PR build is happening here: https://ci.jenkins.io/job/Plugins/job/stash-pullrequest-builder-plugin/view/change-requests/job/jakub-bochenski-patch-1/

> though I guess avoid doing this too often :-)

Sure, I just wasn't paying attention and assumed "Create PR" is the default. Well it isn't if you have write access :)

**Comment by batmat** [comment]
> "Create PR" is the default.

Well, it does. Pushing directly to `master` should be **very** rare. Always going through PRs (but for releases) is definitely the way to go, even more with a co-maintainer.

**Comment by jakub-bochenski** [comment]
@batmat sure, I was talking about what is the default option in the UI (and it's the direct edit).

Also I just posted about it to the mailing list: I would prefer to enable branch protection, but only admins can modify this
screenshot_20190121_145729

**Pull request closed without merging**
