### PR TITLE
Style: always use "if" with braces, remove empty comments

### PR DESCRIPTION
**Pull request by proski**
UPDATED: Very few changes from the original PR survived the "rebase", but they are still useful.

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Thanks but as with the warnings I think it's not worth much without enforcement.

I don't mind having a single big change to reformat code if we can keep it clean afterwards.
I have a working setup for the google formatter from other projects, I'll post a PR

**Comment by proski** [comment]
This PR can still be a stepping stone in that direction. It would make the subcequent changes shorter and easier to review.

**Comment by jakub-bochenski** [comment]
> This PR can still be a stepping stone in that direction. It would make the subcequent changes shorter and easier to review.

While I'm usually all for incremental changes, in this case (automatic reformat) I think it's better to have it in one revision.
It's easier to skip one reformat revision than several if you are trying to work with blame etc.

Can you take a look at #54 ?

**Comment by proski** [comment]
I assumed automatic reformatting the whole codebase would raise objections. But if nobody objects, then #54 should be merged first.
This PR includes some manual changes. I added braces to every `if` and removed some empty comments. I'll be able to "rebase" this PR by formatting the base and the top of the PR and finding the difference. So I don't want to close this PR.

**Comment by jakub-bochenski** [comment]
I think we can close this since the bulk reformat has been merged

**Comment by proski** [comment]
Actually, this PR became very different after "rebasing" on top of the current master. "Rebasing" means that I formatted the base and the top of the PR and applied the difference to the current master branch.

The only surviving changes are the ones I made manually, specifically changes to `if` and to the comments. I'm going to resubmit my PR under another number to avoid confusion.

**Pull request closed without merging**
