### PR TITLE
Add ability to merge on build success

### PR DESCRIPTION
**Pull request by lwalkera**
Adds ability to merge a PR on build success. Uses PR version from REST API to make sure PR isn't stale after the build is done.

Also cleans up some trailing whitespace.

### CODE REVIEW

**Comment by nemccarthy** [comment]
this is useful! could you fix the merge conflicts and we'll get it into a new release

**Comment by lwalkera** [comment]
I'll try to get it fixed up by next week.

**Comment by lwalkera** [comment]
There were some issues I found testing this that will require a bit more work.

Since this modifies the target branch, the spot where we get the PR info will probably have to move to the onStarted step instead of the cron run step so that we don't start a build with the wrong SHA1 and waste test time on old code.

**Comment by nemccarthy** [comment]
@lwalkera was this okay to be merged?

**Comment by lwalkera** [comment]
It will work mostly, but there is a race that I fixed locally. The race happens if you're using the "merge" refspec that's automatically generated when a PR is opened, and when there are many PRs for a particular repo and the Stash server is heavily loaded.
Sometimes the other PRs that are open haven't updated their 'merge' refspec, and if Jenkins kicks off another build during the update, it will fail to fetch the correct revision. I added some code to verify that all the PRs have the the new SHA of the destination branch before finishing the job and it seems to be working ok here for us. I'll try to clean up the code and make a new PR here.
There's also a minor bug with the latest REST API in Bitbucket where it expects the merge message as part of the POST request, whereas in the version of Stash this was developed for that was optional.

**Pull request merged**
