### PR TITLE
Add BitBucket Server's build status API support

### PR DESCRIPTION
**Pull request by ynojima**
BitBucket Server provides build status API.
API doc: https://developer.atlassian.com/static/rest/bitbucket-server/4.5.1/bitbucket-build-rest.html

By using this API, pullrequest builder can tell BitBucket Server whether the pullrequest pass CI test or not, and BitBucket Server utilize build status to determine to block merge.

### CODE REVIEW

**Comment by nickbroon** [comment]
You should probably submit this PR upstream to nemccarthy/stash-pullrequest-builder-plugin

**Comment by rouke-broersma** [comment]
@nickbroon I do not agree
This repository is the canonical plugin source and should thus be seen as the upstream.

See https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Prerequisites

**Comment by nickbroon** [comment]
This might technically be considered canonical but I've always submitted all my PR direct to @nemccarthy as he is the maintainer. He's most likely just going to push changes from his repo any how when he makes a release, and they will then appear here.

**Comment by ynojima** [comment]
@nickbroon, Mobrockers, Thank you for your comments. I'll submit PR to nemccarthy/stash-pullrequest-builder-plugin to get his attention.

**Comment by nemccarthy** [comment]
Why use this instead of just using the stash notifier plugin (which this plugin is designed to work with)?

**Comment by nemccarthy** [comment]
AS discussed this is done by the stash notifier plugin for now so closing this. Thanks for the contribution!

**Pull request closed without merging**
